### PR TITLE
chore: bump nibiru submodule and unhide protojs and gql so we can tra…

### PR DESCRIPTION
**Pull request by cgilbe27**
…ck changes to external APIs

## Summary by CodeRabbit

- **New Features**
	- Introduced multiple TypeScript interfaces for managing various modules including inflation, oracle, and devgas, enhancing the framework for blockchain interactions.
	- Added comprehensive query capabilities for inflation-related data and oracle events.
	- Implemented encoding and decoding methods for efficient data handling across different modules.
	- Added event handling for inflation distribution and epoch management.

- **Documentation**
	- Improved structure and clarity of interfaces and methods across multiple files, ensuring better maintainability and usability.

### CODE REVIEW

**Comment by cgilbe27** [comment]
@coderabbitai ignore /src/protojs changes as these are generated

**Comment by cgilbe27** [comment]
@coderabbitai make a committable suggestion with details for the project

**Comment by cgilbe27** [comment]
@coderabbitai what is the file name of this called and where does it go?

**Comment by cgilbe27** [comment]
@coderabbitai I've commited those changes, please re-review this MR

**Review by CalicoNino — APPROVED** [review]

**Pull request merged**
